### ISSUE TITLE
ComponentPropertyTransparency is missing

### ISSUE THREAD

**Issue by vovanec** [arran4/golang-ical#20]
Hi, it'd be nice to have event.SetTransparency() method added, or maybe two separate methods:
event.SetTransparent(), event.SetOpaque()

**Comment by arran4** [comment]
Hi @vovanec 

I had just pushed a change. It's been a while since I wrote the code base so I had to get reacquainted. It looks like when I wrote it, it was designed to be expandable but fit into the narrow purpose I had for it. I hope I can make it more useful to me in the future and improve the internals.. However, I have added what you requested. Can you please let me know if it's usable? -- If not too late.

Regards,
Arran

**Comment by vovanec** [comment]
Thanks for addressing this, looks good @arran4
